language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - sudo apt-get install python-opengl

# Commands to install dependencies
install:
    - pip3 install -e .
    - pip3 install flake8
    - pip3 install coveralls

# Commands to run tests
script:
    # Check the source code for obvious errors
    - python3 -m flake8 . --count --show-source --statistics --select=E901,E999,F821,F822,F823

    # Test the simulator
    - xvfb-run -a -s "-screen 0 1024x768x24 -ac +extension GLX +render -noreset" ./run_tests.sh

after_success:
    - coveralls
